name: seatsio
description: ->
  This is the Flutter version of seatsio SDK.
  It helps you integrate seating charts into Flutter apps.
repository: https://github.com/SongJiaqiang/seatsio-flutter
version: 0.4.0

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  built_collection: ^5.1.1
  built_value: ^8.9.3
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  built_value_generator: ^8.9.3
